// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "f1fd4f9ec6cb331121f70025d20d5d5ee137b3726254a3499909507be8f2b364"
