// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "2090302381892087186162226c3b2c9fde3afaaebf31756ba95e112ab75e2e67"
